# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aseladarshan/Desktop/Semester_5/3Dscanner/visualizer/qtProject/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aseladarshan/Desktop/Semester_5/3Dscanner/visualizer/qtProject/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aseladarshan/Desktop/Semester_5/3Dscanner/visualizer/qtProject/src/CMakeFiles /home/aseladarshan/Desktop/Semester_5/3Dscanner/visualizer/qtProject/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aseladarshan/Desktop/Semester_5/3Dscanner/visualizer/qtProject/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pcl_visualizer

# Build rule for target.
pcl_visualizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcl_visualizer
.PHONY : pcl_visualizer

# fast build rule for target.
pcl_visualizer/fast:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/build
.PHONY : pcl_visualizer/fast

connectionhelper.o: connectionhelper.cpp.o
.PHONY : connectionhelper.o

# target to build an object file
connectionhelper.cpp.o:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/connectionhelper.cpp.o
.PHONY : connectionhelper.cpp.o

connectionhelper.i: connectionhelper.cpp.i
.PHONY : connectionhelper.i

# target to preprocess a source file
connectionhelper.cpp.i:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/connectionhelper.cpp.i
.PHONY : connectionhelper.cpp.i

connectionhelper.s: connectionhelper.cpp.s
.PHONY : connectionhelper.s

# target to generate assembly for a file
connectionhelper.cpp.s:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/connectionhelper.cpp.s
.PHONY : connectionhelper.cpp.s

connector.o: connector.cpp.o
.PHONY : connector.o

# target to build an object file
connector.cpp.o:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/connector.cpp.o
.PHONY : connector.cpp.o

connector.i: connector.cpp.i
.PHONY : connector.i

# target to preprocess a source file
connector.cpp.i:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/connector.cpp.i
.PHONY : connector.cpp.i

connector.s: connector.cpp.s
.PHONY : connector.s

# target to generate assembly for a file
connector.cpp.s:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/connector.cpp.s
.PHONY : connector.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/main.cpp.s
.PHONY : main.cpp.s

moc_viewer.o: moc_viewer.cxx.o
.PHONY : moc_viewer.o

# target to build an object file
moc_viewer.cxx.o:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/moc_viewer.cxx.o
.PHONY : moc_viewer.cxx.o

moc_viewer.i: moc_viewer.cxx.i
.PHONY : moc_viewer.i

# target to preprocess a source file
moc_viewer.cxx.i:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/moc_viewer.cxx.i
.PHONY : moc_viewer.cxx.i

moc_viewer.s: moc_viewer.cxx.s
.PHONY : moc_viewer.s

# target to generate assembly for a file
moc_viewer.cxx.s:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/moc_viewer.cxx.s
.PHONY : moc_viewer.cxx.s

viewer.o: viewer.cpp.o
.PHONY : viewer.o

# target to build an object file
viewer.cpp.o:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/viewer.cpp.o
.PHONY : viewer.cpp.o

viewer.i: viewer.cpp.i
.PHONY : viewer.i

# target to preprocess a source file
viewer.cpp.i:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/viewer.cpp.i
.PHONY : viewer.cpp.i

viewer.s: viewer.cpp.s
.PHONY : viewer.s

# target to generate assembly for a file
viewer.cpp.s:
	$(MAKE) -f CMakeFiles/pcl_visualizer.dir/build.make CMakeFiles/pcl_visualizer.dir/viewer.cpp.s
.PHONY : viewer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pcl_visualizer"
	@echo "... rebuild_cache"
	@echo "... connectionhelper.o"
	@echo "... connectionhelper.i"
	@echo "... connectionhelper.s"
	@echo "... connector.o"
	@echo "... connector.i"
	@echo "... connector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_viewer.o"
	@echo "... moc_viewer.i"
	@echo "... moc_viewer.s"
	@echo "... viewer.o"
	@echo "... viewer.i"
	@echo "... viewer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

